// <auto-generated />
using System;
using LIS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LIS.API.Migrations
{
    [DbContext(typeof(LISAPIContext))]
    [Migration("20260324022210_V02")]
    partial class V02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modelos_LIS.Especialidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("espe_descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("espe_nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("Modelos_LIS.Examenes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("exam_nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("exam_referencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("exam_unidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Examenes");
                });

            modelBuilder.Entity("Modelos_LIS.Medicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("especialidadId")
                        .HasColumnType("integer");

                    b.Property<string>("med_apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("med_cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("med_correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("med_nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("med_password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("med_telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("especialidadId");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("Modelos_LIS.Ordenes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicoId")
                        .HasColumnType("integer");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<bool>("orden_estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("orden_fecha")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("Modelos_LIS.Pacientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Paciente_Fecha_Nac")
                        .HasColumnType("date");

                    b.Property<string>("pac_apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pac_cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pac_correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pac_nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pac_telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Modelos_LIS.Resultados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamenId")
                        .HasColumnType("integer");

                    b.Property<int>("OrdenId")
                        .HasColumnType("integer");

                    b.Property<string>("res_comentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("res_valor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExamenId");

                    b.HasIndex("OrdenId");

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("Modelos_LIS.Medicos", b =>
                {
                    b.HasOne("Modelos_LIS.Especialidades", "Especialidad")
                        .WithMany()
                        .HasForeignKey("especialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("Modelos_LIS.Ordenes", b =>
                {
                    b.HasOne("Modelos_LIS.Medicos", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos_LIS.Pacientes", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Modelos_LIS.Resultados", b =>
                {
                    b.HasOne("Modelos_LIS.Examenes", "Examen")
                        .WithMany()
                        .HasForeignKey("ExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos_LIS.Ordenes", "Orden")
                        .WithMany()
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Examen");

                    b.Navigation("Orden");
                });
#pragma warning restore 612, 618
        }
    }
}
